version: '3.8'

services:
  servidor:
    build:
      context: .
    network_mode: host  # Acceso directo a la red del host para usar wlan0
    environment:
      POSTGRES_DB: red_datos
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: red_datos
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./DB.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

